version: '3'
services:
  gateway:
    ports:
      - "8080:8080"
    build:
      dockerfile: ./docker/gateway/Dockerfile
  fastapi:
    environment:
      - UVICORN_LOG_LEVEL=${UVICORN_LOG_LEVEL}
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    volumes:
      - ./src:/usr/src/app

